// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import weatherapi "github.com/kniepok/weatherAPI"

// BookmarksStorage is an autogenerated mock type for the BookmarksStorage type
type BookmarksStorage struct {
	mock.Mock
}

// AddBookmark provides a mock function with given fields: _a0
func (_m *BookmarksStorage) AddBookmark(_a0 *weatherapi.Location) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*weatherapi.Location) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBookmarks provides a mock function with given fields:
func (_m *BookmarksStorage) GetBookmarks() ([]*weatherapi.Location, error) {
	ret := _m.Called()

	var r0 []*weatherapi.Location
	if rf, ok := ret.Get(0).(func() []*weatherapi.Location); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*weatherapi.Location)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
